spring:
  application:
    name: LTJava

  datasource:
    url: jdbc:mysql://localhost:3306/LTJavaTest?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password: ${DB_PASSWORD:default_pass}
    hikari:
    hibernate:
      ddl-auto: update # dev, sau đổi validate
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 20
          fetch_size: 50
        order_inserts: true

  # ===== REDIS =====
  data:
    redis:
      host: localhost
      port: 6379

app:
  storage:
    pdf-dir: uploads/pdfs

  upload:
    base-dir: "src/main/resources/uploads"

server:
  port: 8081

gemini:
  api:
    key: ${GEMINI_API_KEY:}
    url: https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent
